version: '1'
services:
  database:
    image: postgres:14.6
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fcb
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
    ports:
      - 8001:8001
    environment:
      - DATABASE_URL=postgresql://user:password@database:5432/fcb
      - PORT=8001
    depends_on:
      - database

  client:
    build:
      context: ./client
    ports:
      - '3000:3000'
    depends_on:
      - server

volumes:
  postgres-data:
